//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace circus.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListPerformance
    {
        public int ID { get; set; }
        public Nullable<int> IdArtist { get; set; }
        public string NamePerformance { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
